# Generated by Django 4.2.20 on 2025-04-09 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QA_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='answerlike',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QA_project.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
