# Generated by Django 4.2.20 on 2025-04-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA_project', '0004_remove_answer_created_at_remove_question_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='edited_at',
        ),
    ]
