# Generated by Django 4.2.20 on 2025-05-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_project', '0006_remove_profile_password_answer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='edited_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='edited_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
